name: Build and create MSI package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Find msbuild.exe
      shell: pwsh
      run: |
        $msbuildPath = (Get-Command -Name msbuild -ErrorAction Stop).Path
        echo "MSBuildPath=$msbuildPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Restore NuGet packages
      run: ${{ env.MSBuildPath }} -t:Restore

    - name: Build solution
      run: ${{ env.MSBuildPath }} -p:Configuration=Release

    - name: Download Inno Setup
      run: |
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"
        Start-Process -FilePath .\is.exe -ArgumentList "/VERYSILENT", "/NORESTART", "/SUPPRESSMSGBOXES", "/SP-", "/LOG=innosetup.log" -Wait -NoNewWindow

    - name: Compile Inno Setup script
      run: |
        $env:ISCC = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
        & $env:ISCC /O"output" /F"MyInstaller" installer.iss"  # Adjust the script path and output name

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Installer
        path: "output\\G910 Macro Viewer.msi"
