name: Build and create MSI package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Create temporary MSBuild console app
      run: |
        dotnet new console -n TempMSBuildApp
        cd TempMSBuildApp
        dotnet add package Microsoft.Build.Runtime --version 17.5.0
        Add-Content -Path Program.cs -Value @"
          using Microsoft.Build.Framework;
          using Microsoft.Build.Logging;
          using Microsoft.Build.Locator;

          MSBuildLocator.RegisterDefaults();
          var buildResult = Build.BuildEngine.BuildProjectFile(@"""${{ github.workspace }}\G910 Macro Viewer.sln""", null, null, new ConsoleLogger());
          if (!buildResult) Environment.Exit(1);
        "@

    - name: Build solution
      run: |
        cd TempMSBuildApp
        dotnet run

    - name: Download Inno Setup
      run: |
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"
        Start-Process -FilePath .\is.exe -ArgumentList "/VERYSILENT", "/NORESTART", "/SUPPRESSMSGBOXES", "/SP-", "/LOG=innosetup.log" -Wait -NoNewWindow

    - name: Compile Inno Setup script
      run: |
        $env:ISCC = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
        & $env:ISCC /O"output" /F"MyInstaller" installer.iss"  # Adjust the script path and output name

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Installer
        path: "output\\G910 Macro Viewer.msi"
