name: Build and create MSI package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Setup MSBuild.exe
      # You may pin to the exact commit or the version.
      # uses: warrenbuckley/Setup-MSBuild@1176db82e64cd53b4944f0e57c2abec104b4782d
      uses: warrenbuckley/Setup-MSBuild@v1
      
    - name: MSBuild
      run: |
        "G910 Macro Viewer.csproj" -t:rebuild -verbosity:diag -property:Configuration=Release
      
    - name: Download Inno Setup
      run: |
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"
        Start-Process -FilePath .\is.exe -ArgumentList "/VERYSILENT", "/NORESTART", "/SUPPRESSMSGBOXES", "/SP-", "/LOG=innosetup.log" -Wait -NoNewWindow

    - name: Compile Inno Setup script
      run: |
        $env:ISCC = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
        & $env:ISCC /O"output" /F"MyInstaller" installer.iss"  # Adjust the script path and output name

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Installer
        path: "output\\G910 Macro Viewer.msi"
