name: Build and Package

on:
  push:
    branches:
      - main  # Adjust this to match your default branch name
  pull_request:
    branches:
      - main  # Adjust this to match your default branch name

jobs:
  build_and_package:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: msbuild /p:Configuration=Release

    - name: Download Inno Setup
      run: |
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"
        Start-Process -FilePath .\is.exe -ArgumentList "/VERYSILENT", "/NORESTART", "/SUPPRESSMSGBOXES", "/SP-", "/LOG=innosetup.log" -Wait -NoNewWindow

    - name: Compile Inno Setup script
      run: |
        $env:ISCC = "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe"
        & $env:ISCC /O"output" /F"MyInstaller" installer.iss"  # Adjust the script path and output name

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Installer
        path: "output\\G910 Macro Viewer.msi"
